### ISSUE TITLE
Show optional/required in param table in docs

### ISSUE THREAD

**Issue by janpio** [fastlane/docs#711] opened 2018-09-01 00:43 UTC
New column that marks params that are optional/required

**Comment by KrauseFx** [comment] 2018-09-05 20:58
It's a little tricky with `required`, as often those values are determined completely automatically in most cases, so it might be confusing, no?

**Comment by janpio** [comment] 2018-09-05 21:27
Might be an issue, yes. 
But @revolter handled that beautifully for the default values, maybe in combination with this it could work. 

It would definitely be very good when starting to use an action. The trial and error method of course also works, but needs a lot more time ;)

**Comment by revolter** [comment] 2018-09-06 10:14
Duplicate of the (newly added) `optional` checklist item in #476.

**Closed by revolter** 2018-09-06 10:14 UTC
