### ISSUE TITLE
is any changes for hybrid app build and deployment process?

### ISSUE THREAD

**Issue by shindekaps** [fastlane/docs#576] opened 2018-04-06 12:15 UTC
Now days most of the apps developed using hybrid frameworks like Cordova. So is any chances for hybrid application.

**Comment by joshdholtz** [comment] 2018-04-06 12:28
@shindekaps Heyyy 👋 Are you asking if...
1) Does fastlane support hybrid frameworks like Cordova?
or
2) Can documentation be added for building with hybrid frameworks?

**Comment by shindekaps** [comment] 2018-04-06 12:32
Yes 
I am asking for both.

**Comment by janpio** [comment] 2018-04-06 13:45
Well, I wrote "a bit" about using Fastlane with Ionic at https://ionic.zone/fastlane
As Ionic uses Cordova in the background, this all applies to normal Cordova apps as well.

**Comment by getaaron** [comment] 2018-04-06 14:39
There’s also some support in `fastlane init` for setting up a React Native project

**Comment by joshdholtz** [comment] 2018-04-09 11:40
I _do_ think we maybe could add a "Hybrid" section and has some references and best practices sections so its easier to find for people 🤔 Thoughts?

**Comment by janpio** [comment] 2018-08-01 08:58
Duplicate of https://github.com/fastlane/docs/issues/626

**Closed by janpio** 2018-08-01 08:58 UTC
